### ISSUE TITLE
wiringPi

### ISSUE THREAD

**Issue by Bodata** [akkenoth/rapp-elektron-cupholder#1]
Hi,
Sorry to miss use this project, but i could not find a issues option in your wiringPi project.

I have odroid C1+ and i want to connect a VL6180X Time-of-Flight Distance sensor.
I was very pleased to find your project.
The odroid has Ubuntu OS. 
I downloaden the wiringPI and want to compile it but i get an error.
It misses pthreads if i understand correctly, could you help me ?

Regard,
Peter

**Comment by mjbogusz** [comment]
Indeed the issues tab was disabled for that repository, I don't know why. Possibly GitHub doesn't create those by default for forks.
I've copied the issue to proper repo ([mjbogusz/wiringPi issue#2](https://github.com/mjbogusz/wiringPi/issues/2)) and I'll try to help you there.
